# URD (User Requirements Document) Configuration
# Top level of V-model - no parent

settings:
  digits: 3              # Use 3 digits for numbering (URD-001, URD-002, etc.)
  itemformat: yaml       # Store requirements as YAML files
  # No parent (top of hierarchy)
  prefix: URD            # Prefix for all user requirements
  sep: '-'               # Separator between prefix and number

# Optional: Additional metadata
metadata:
  name: User Requirements
  description: User-level requirements describing WHAT users need
  level: 1
  version: 1.0
