# SWD (Software Design Document) Configuration
# Third level of V-model - parent is SRD

settings:
  digits: 3              # Use 3 digits for numbering (SWD-001, SWD-002, etc.)
  itemformat: yaml       # Store requirements as YAML files
  parent: SRD            # Parent is SRD (System Requirements)
  prefix: SWD            # Prefix for all software requirements
  sep: '-'               # Separator between prefix and number

# Optional: Additional metadata
metadata:
  name: Software Requirements
  description: Software-level requirements describing HOW software implements system requirements
  level: 3
  version: 1.0
