# SRD (System Requirements Document) Configuration
# Second level of V-model - parent is URD

settings:
  digits: 3              # Use 3 digits for numbering (SRD-001, SRD-002, etc.)
  itemformat: yaml       # Store requirements as YAML files
  parent: URD            # Parent is URD (User Requirements)
  prefix: SRD            # Prefix for all system requirements
  sep: '-'               # Separator between prefix and number

# Optional: Additional metadata
metadata:
  name: System Requirements
  description: System-level requirements describing HOW the system provides capabilities
  level: 2
  version: 1.0
