#!/usr/bin/env python3
"""Regenerate .dotstop.dot from requirement files under reqs/.

This writes a minimal dot file listing items found in the repo. It helps
trudag locate items when the auto-generated dot is stale or inconsistent.
"""
from pathlib import Path
import hashlib

REQ_DIR = Path('reqs')
OUT = Path('.dotstop.dot')

items = []
for p in sorted(REQ_DIR.rglob('*.yml')):
    if p.name == '.doorstop.yml' or 'templates' in p.parts:
        continue
    # derive item id from filename or ref in YAML
    stem = p.stem
    # compute a lightweight sha of contents
    content = p.read_bytes()
    sha = hashlib.sha256(content).hexdigest()[:64]
    items.append((stem, sha))

with OUT.open('w') as f:
    f.write('# Auto-regenerated by scripts/regenerate_dotstop_dot.py\n')
    f.write('digraph G {\n')
    for id, sha in items:
        # find the file matching this id to include a path attribute
        candidates = list(Path('reqs').rglob(f'{id}.yml')) + list(Path('reqs').rglob(f'{id}.yaml'))
        path_attr = candidates[0].as_posix() if candidates else ''
        f.write(f'"{id}" [sha="{sha}" path="{path_attr}"];\n')
    f.write('}\n')

print(f'Wrote {OUT} with {len(items)} items')
