# LLTC (Low-Level Test Cases) Configuration
# Fourth level of V-model - parent is SWD

settings:
  digits: 3              # Use 3 digits for numbering (LLTC-001, LLTC-002, etc.)
  itemformat: yaml       # Store requirements as YAML files
  parent: SWD            # Parent is SWD (Software Requirements)
  prefix: LLTC           # Prefix for all test cases
  sep: '-'               # Separator between prefix and number

# Optional: Additional metadata
metadata:
  name: Low-Level Test Cases
  description: Test cases verifying that software requirements are correctly implemented
  level: 4
  version: 1.0
